### ISSUE TITLE
MT9 - Arlan

### ISSUE THREAD

**Issue by zegildo** [zegildo/DataMining#44]
@ArlanMDs,

Em sua pasta MT9 há 3 arquivos, por favor, deixe **apenas**:

1. O .csv final ;
2.  código que utilizou para chegar a esta configuração final. Se fez no excel, o arquivo excel, se fez na mão o procedimento em um .txt, se fez em .c ou .java ou .py o código utilizado.

**Comment by ArlanMDs** [comment]
Feito pull request #48 para corrigir o problema

**Comment by zegildo** [comment]
ok.
